import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast"; // Import the Toaster component
import { ReduxProvider } from "@/redux/provider";
import "./globals.css"; // Ensure you have global styles

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>
          <main>{children}</main>
          <Toaster position="top-center" />
        </body>
      </ReduxProvider>
    </html>
  );
}
